### ISSUE TITLE
Attach animation to h3 with attributes

### ISSUE THREAD

**Issue by joshm1204** [mciastek/sal#110]
I want all my h3 to have specific attributes.

                <h3 
                  sal-animate" data-sal="zoom-in" 
                  data-sal-duration="500" 
                  data-sal-delay="200" 
                  data-sal-easing="ease-out-cubic"
                >

Instead of manually adding it to each h3, I think there is a way to attach it with the selector, but I can't make sense of the instructions. I read all of it.  Can you please provide an example of how this is done?

I see that I can set CSS

[data-sal] {
  transition-duration: 500;
  transition-delay: 200;
}

How do I set the easing and animate?

**Comment by gingerchew** [comment]
First thing, CSS doesn't allow for unit-less values when dealing with transitions. 
```css
.my-transition-el {
	/* this is invalid since 0 has no unit, even though 0 normally does not need a unit */
	transition: transform 0 ease;
	/* this is since we've added a time unit */
	transition: transform 0s ease;
}
```

Sal.js abstracts that unit using `data-sal-*` attributes, by creating a set of defaults like `[data-sal-duration="300"]` which translates to the proper CSS:

```css
[data-sal][data-sal-duration="300"]  {
	transition-duration: 300ms; /** Notice the ms unit that has been added */
}
```
Maybe the missing units is the source of the issue?

Since you are trying to change the duration and delay on the `[data-sal]` elements,  you could add this to the CSS:

```css
[data-sal] {
	--sal-duration: 500ms;
	--sal-delay: 200ms;
	--sal-easing: ease-in-out;
}
```

This doesn't mess with your ability to later change the values like this:

```html
<p data-sal="fade" style="--sal-duration: 125ms;">My specific super special Sal duration</p>
```

So if you wanted to do this for *just* the h3 elements, you can do:

```css
h3[data-sal]  {
	--sal-duration: 500ms;
	--sal-delay: 200ms;
	--sal-easing: ease-in-out;
}
```

Hopefully this helps!
