### ISSUE TITLE
Binding to class

### ISSUE THREAD

**Issue by Neci92** [mciastek/sal#19]
Hello! Is there any way to bind certain animation to a class so every element with that class acts same when scrolled into view?

**Comment by mciastek** [comment]
You can create your own animation and launch it when specific element gets `sal-animate` class. For example:

```scss
.my-animation {
  transform: rotate(90deg) scale(0.7);
}

.my-animation.sal-animate {
  // animate to initial state
  transform: none;
}
```
