### ISSUE TITLE
Use custom properties for duration and delay

### ISSUE THREAD

**Issue by rbottomley** [mciastek/sal#20]
I have a suggestion: instead of having fixed choices for duration and delay, use CSS custom properties instead.

Change the CSS to:

`[data-sal] {`
`  transition-duration: var(--animation-duration, $sal-animation-duration);`
`  transition-delay: var(--animation-delay, $sal-animation-delay);`
`}`

This gives you the existing default values, but overriding them is much easier:

`<div data-sal="fade" style="--animation-duration: 2000ms">...`

**Comment by mciastek** [comment]
Great idea! 🎉  If I may, I'd prefer to prefix variables, like `--sal-animation-delay`. Additionally, it needs to have a fallback for browsers that doesn't support CSS variables. To cover the case, when you include polyfill for Intersection Observer, but you don't want to add polyfill for CSS variables. For example:

```css
[data-sal] {
  transition-duration: $sal-animation-duration;
  transition-delay: $sal-animation-delay;
  transition-duration: var(--animation-duration, $sal-animation-duration);
  transition-delay: var(--animation-delay, $sal-animation-delay);
}
```
