### ISSUE TITLE
Configurable scss 

### ISSUE THREAD

**Issue by Levdbas** [mciastek/sal#81]
Hi and first of all, thank you! Sal feels like the spiritual successor of AOS.
One thing I would really love to see is a way to customize the generated css.

This should be possible by making over-writable scss variables by using the !default parameter.

Thinks I suggest in the scss:

**Overwritable easings**
This way you are able to remove easings you don't use and make the bundle size smaller.
```scss
$sal-easings: (
....
) !default;
```

**Configurable timings and delays**
This way you are able to add or remove timings.
```scss

$amount-of-timings: 40 !default;
$amount-of-delay: 20 !default;

@for $i from 4 through $amount-of-timings {
  [data-sal][data-sal-duration='#{$i * 50}'] {
    transition-duration: #{$i * 0.05}s;
  }
}

@for $i from 1 through $amount-of-delays {
  [data-sal][data-sal-delay='#{$i * 50}'] {
    transition-delay: #{$i * 0.05}s;
  }
}
```

I'd like to hear your thoughts!
